"""add_address_and_member_fields

Revision ID: 2c6672df2e12
Revises: 0d1d276e5bfa
Create Date: 2026-01-19 19:39:34.767163

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c6672df2e12'
down_revision: Union[str, Sequence[str], None] = '0d1d276e5bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('marriage_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('spouse_name', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('profession_of_faith_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('admission_type', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('origin_church', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('tenants', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('tenants', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'postal_code')
    op.drop_column('tenants', 'state')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'neighborhood')
    op.drop_column('tenants', 'complement')
    op.drop_column('tenants', 'number')
    op.drop_column('tenants', 'street')
    op.drop_column('members', 'origin_church')
    op.drop_column('members', 'admission_type')
    op.drop_column('members', 'admission_date')
    op.drop_column('members', 'profession_of_faith_date')
    op.drop_column('members', 'spouse_name')
    op.drop_column('members', 'marriage_date')
    # ### end Alembic commands ###
