apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: filadelfias

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - web.yaml
  - cloudflared.yaml
  - network-policies.yaml

images:
  - name: ghcr.io/l3co/filadelfias-backend
    newName: ghcr.io/l3co/filadelfias-backend
    newTag: latest
  - name: ghcr.io/l3co/filadelfias-web
    newName: ghcr.io/l3co/filadelfias-web
    newTag: latest
