"""
Shared metadata for bible versions and book labels.
"""

from __future__ import annotations

DEFAULT_VERSION = "nvi"

BOOK_NAMES = {
    "gn": "Gênesis",
    "ex": "Êxodo",
    "lv": "Levítico",
    "nm": "Números",
    "dt": "Deuteronômio",
    "js": "Josué",
    "jz": "Juízes",
    "rt": "Rute",
    "1sm": "1 Samuel",
    "2sm": "2 Samuel",
    "1rs": "1 Reis",
    "2rs": "2 Reis",
    "1cr": "1 Crônicas",
    "2cr": "2 Crônicas",
    "ed": "Esdras",
    "ne": "Neemias",
    "et": "Ester",
    "job": "Jó",
    "sl": "Salmos",
    "pv": "Provérbios",
    "ec": "Eclesiastes",
    "ct": "Cânticos",
    "is": "Isaías",
    "jr": "Jeremias",
    "lm": "Lamentações",
    "ez": "Ezequiel",
    "dn": "Daniel",
    "os": "Oséias",
    "jl": "Joel",
    "am": "Amós",
    "ob": "Obadias",
    "jn": "Jonas",
    "mq": "Miquéias",
    "na": "Naum",
    "hc": "Habacuque",
    "sf": "Sofonias",
    "ag": "Ageu",
    "zc": "Zacarias",
    "ml": "Malaquias",
    "mt": "Mateus",
    "mc": "Marcos",
    "lc": "Lucas",
    "jo": "João",
    "at": "Atos",
    "rm": "Romanos",
    "1co": "1 Coríntios",
    "2co": "2 Coríntios",
    "gl": "Gálatas",
    "ef": "Efésios",
    "fp": "Filipenses",
    "cl": "Colossenses",
    "1ts": "1 Tessalonicenses",
    "2ts": "2 Tessalonicenses",
    "1tm": "1 Timóteo",
    "2tm": "2 Timóteo",
    "tt": "Tito",
    "fm": "Filemom",
    "hb": "Hebreus",
    "tg": "Tiago",
    "1pe": "1 Pedro",
    "2pe": "2 Pedro",
    "1jo": "1 João",
    "2jo": "2 João",
    "3jo": "3 João",
    "jd": "Judas",
    "ap": "Apocalipse",
}

ALL_VERSIONS = [
    {
        "code": "nvi",
        "name": "Nova Versão Internacional",
        "description": "Linguagem moderna e acessível",
        "is_remote": False,
    },
    {
        "code": "acf",
        "name": "Almeida Corrigida Fiel",
        "description": "Tradução clássica e fiel aos originais",
        "is_remote": False,
    },
    {
        "code": "aa",
        "name": "Almeida Atualizada",
        "description": "Equilíbrio entre tradição e clareza",
        "is_remote": False,
    },
    {
        "code": "ara",
        "name": "Almeida Revista e Atualizada",
        "description": "Texto Tradicional e Atual (On-line)",
        "is_remote": True,
    },
]

LOCAL_VERSION_CODES = ["nvi", "acf", "aa"]
